//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporOrganizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etkinlik()
        {
            this.Kullanici = new HashSet<Kullanici>();
        }
    
        public int EtkinlikId { get; set; }
        public string EtkinlikAdi { get; set; }
        public int TipId { get; set; }
        public int MekanID { get; set; }
        public Nullable<System.DateTime> EtkinlikTarihi { get; set; }
        public Nullable<int> Kontenjan { get; set; }
        public int isActive { get; set; }
        public int Sid { get; set; }
    
        public virtual EtkinlikTipi EtkinlikTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici { get; set; }
    }
}
