//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporOrganizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HataLoglari
    {
        public int id { get; set; }
        public string DosyaAdi { get; set; }
        public string MethodAdi { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> ColumnNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> trh { get; set; }
    }
}
